name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.14.0'
      - name: Setup PNPM
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.5.4
          run_install: |
            - args: [--frozen-lockfile, --silent]
      - name: Build
        run: node scripts/build.js
      - name: Test
        run: pnpm run coverage

      - run: bash <(curl -s https://codecov.io/bash)
