name: Release Extensions

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

jobs:
  extensions:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && contains(github.head_ref, 'releases/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.14.0'

      - name: Setup PNPM
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.5.4
          run_install: |
            - args: [--frozen-lockfile, --silent]

      - name: Build Packages
        run: |
          node scripts/build.js
          pnpm recursive --filter @vuedx/typescript-plugin-vue run build

      - name: Publish Insiders Extension
        run: |
          pnpm recursive --filter ./extensions run release

      - id: create_release
        name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            TODO: Add release notes.
          draft: false
          prerelease: false

      - name: Upload Vue extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extensions/vscode-vue/vue.vsix
          asset_name: vscode-vue-${{ github.ref }}.vsix
          asset_content_type: application/octet-stream

      - name: Upload Vue Language Features extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extensions/vscode-vue-language-features/vue-language-features.vsix
          asset_name: vscode-vue-language-features-${{ github.ref }}.vsix
          asset_content_type: application/octet-stream
